"""System instructions and prompt templates for OLIVER.

The system prompt plus the repository map form the stable prefix of every
conversation, so nothing time-dependent is ever placed in them (that keeps
provider-side prompt caching effective).
"""

import json

SYSTEM_PROMPT = """You are OLIVER, an autonomous software engineer working inside a code repository.
Your job is to resolve the task with a correct, minimal change that the harness can verify.

How to work:
1. Understand. Read the task, then locate the relevant code with search_repo, list_files and read_file. Prefer targeted reads with line ranges over whole files.
2. Reproduce. When the task describes a bug, write a small failing test in a new test file (or a short script) and run it before changing code.
3. Fix. Make the smallest change that fixes the root cause. Use edit_file for existing files, copying old_text exactly from read_file output without the line-number prefix. Use write_file only for new files.
4. Verify. Run the relevant tests with run_tests or run_command and read the results.
5. Finish. Call finish with a short summary of the root cause and the change.

Rules:
- Never modify or delete existing tests to make them pass. You may add new tests.
- Keep the change focused on the task: no unrelated refactors, renames or formatting churn.
- Remove any debugging output you add before calling finish.
- When a tool returns an error, read it and adjust. Repeating the same call gives the same result.
- All paths are relative to the repository root.
- After finish, the harness runs its own verification. The task counts as done only when that evidence passes."""

PLAN_REQUEST = """PLANNING PHASE. Only read_file, search_repo and list_files are available now.
Investigate until you can name the root cause, then reply with only a JSON object in a ```json fenced block:
{
  "root_cause": "one or two sentences",
  "files_to_change": ["path/to/file.py"],
  "steps": ["short imperative step"],
  "reproduction_command": "a shell command that fails before the fix and passes after it, or an empty string",
  "tests_to_run": ["tests/test_example.py"]
}
Use at most 10 steps. Do not edit anything yet."""

PLAN_FINAL_CALL = """Stop exploring now. Reply with the JSON plan in a ```json fenced block, based on what you have found so far."""

PLAN_REPAIR = """That reply did not contain a valid JSON plan. Reply again with only the JSON object in a ```json fenced block, using the fields root_cause, files_to_change, steps, reproduction_command and tests_to_run."""

NUDGE = """You replied without calling a tool. Continue working with the tools, or call finish if the change is complete and verified."""

REVIEW_SYSTEM = """You are OLIVER's reviewer. You check a verified code change against its task and report only concrete defects."""

TEXT_PROTOCOL_HEADER = """TOOL PROTOCOL
To call a tool, reply with one or more blocks written exactly like this:
<tool_call>{"name": "read_file", "arguments": {"filepath": "src/app.py"}}</tool_call>
Put only the JSON object inside each block. Tool results arrive in the next message.
Available tools:"""

RECOVERY_GUIDANCE = {
    'syntax_error': 'A changed file does not parse. Fix the syntax before anything else.',
    'import_error': 'The code fails to import. Check names, import paths and circular imports.',
    'regression': 'Your change broke tests that passed before it. Keep the fix but restore the old behaviour for those cases.',
    'reproduction_failed': 'The reproduction command still fails, so the root cause is not fixed yet. Re-check it before editing again.',
    'test_failure': 'Tests related to the task still fail. Read the failure output and fix the cause.',
    'new_test_failure': 'A test you added still fails. Either the fix is incomplete or the new test is wrong.',
    'timeout': 'A command timed out. Look for infinite loops or slow operations and run narrower tests.',
    'no_changes': 'No file was changed. The task needs a code change.',
    'loop': 'You kept repeating the same action. Stop and choose a different approach.',
    'unknown': 'Verification failed. Read the evidence and fix the cause.',
}


def build_system_prompt(repo_map):
    return SYSTEM_PROMPT + '\n\nREPOSITORY MAP (generated by the harness)\n' + repo_map


def build_task_message(task, test_command, baseline_summary, hints):
    lines = ['TASK', task.strip(), '', 'REPOSITORY FACTS (collected by the harness)']
    lines.append('- Test command: ' + (test_command if test_command else 'none detected'))
    lines.append('- Baseline tests before any change: ' + baseline_summary)
    if hints['paths']:
        lines.append('- Paths mentioned in the task: ' + ', '.join(hints['paths'][:10]))
    if hints['errors']:
        lines.append('- Errors mentioned in the task: ' + ', '.join(hints['errors'][:10]))
    return '\n'.join(lines)


def plan_request(replan_note):
    if not replan_note:
        return PLAN_REQUEST
    return 'REPLANNING. ' + replan_note + '\n\n' + PLAN_REQUEST


def replan_note(signature, memory_text):
    return ('The previous approach failed twice with the same error:\n' + signature
            + '\nThe repository was rolled back to the last good state. '
            + 'Approaches and findings so far (do not repeat failed approaches):\n' + memory_text)


def execute_request(plan):
    return ('EXECUTION PHASE. Follow this plan, adjusting it if the evidence disagrees:\n'
            + json.dumps(plan, indent=2)
            + '\nAll tools are available now. Make the change, verify it, then call finish.')


def recovery_prompt(failure, attempt, max_attempts, memory_text):
    kind = failure['kind']
    guidance = RECOVERY_GUIDANCE[kind] if kind in RECOVERY_GUIDANCE else RECOVERY_GUIDANCE['unknown']
    return ('VERIFICATION FAILED (attempt {0} of {1}): {2}\n\nEvidence from the harness:\n{3}\n\n{4}\n\n'
            'Working memory:\n{5}\n\nFix the problem, re-run the relevant checks, then call finish again.').format(
        attempt, max_attempts, failure['headline'], failure['details'], guidance, memory_text)


def loop_warning(count):
    return ('You have made the same call {0} times in a row with the same arguments. '
            'It will not give a different result. Choose a different action.').format(count)


def tool_not_allowed(name, phase, allowed):
    return 'ERROR: tool "{0}" is not available in the {1} phase. Available tools: {2}.'.format(
        name, phase, ', '.join(allowed) if allowed else 'none')


def review_request(task, patch, verification_summary):
    return ('REVIEW. The harness verified the change below.\n\nTask:\n' + task.strip()
            + '\n\nVerification:\n' + verification_summary
            + '\n\nDiff:\n```diff\n' + patch + '\n```\n\n'
            'Reply with only a JSON object: {"verdict": "approve" or "revise", "issues": ["concrete problem"]}.\n'
            'Use "revise" only for a concrete defect: the task is not fully addressed, a case named in the task is '
            'missed, debugging output was left behind, or unrelated code was changed.')


def review_feedback(issues):
    return ('REVIEW FEEDBACK. A review of your verified change found these problems:\n'
            + '\n'.join('- ' + issue for issue in issues)
            + '\nFix them, keep the tests passing, then call finish again.')


def render_tool_catalog(tool_specs):
    lines = [TEXT_PROTOCOL_HEADER]
    for spec in tool_specs:
        function = spec['function']
        properties = function['parameters']['properties']
        required = function['parameters']['required']
        params = []
        for name in properties:
            marker = '' if name in required else '?'
            params.append(name + marker + ': ' + properties[name]['type'])
        lines.append('- ' + function['name'] + '(' + ', '.join(params) + '): ' + function['description'])
    return '\n'.join(lines)
